version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: localpass
      POSTGRES_USER: localuser
      POSTGRES_DB: driders
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://localuser:localpass@db:5432/driders
      REDIS_URL: redis://redis:6379
      JWT_SECRET: devsecret
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  admin:
    build: ./admin
    environment:
      NEXT_PUBLIC_BACKEND: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
